spring:
  application:
    name: base
  datasource:
    url: jdbc:postgresql://localhost:5432/auction_db
    username: postgres
    password: 12345
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
logging:
  level:
    root=INFO: